/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndktutorial_VectorNat */

#ifndef _Included_com_example_ndktutorial_VectorNat
#define _Included_com_example_ndktutorial_VectorNat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndktutorial_VectorNat
 * Method:    norm
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_com_example_ndktutorial_VectorNat_norm
  (JNIEnv *, jclass, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
